### ISSUE TITLE
安装mana后，导入路径报错

### ISSUE THREAD

**Issue by Andrewpqc** [neo1218/mana#21]

**Comment by Andrewpqc** [comment]
下面是报错信息:
``` bash 
andrew@andrew-Lenovo:~/桌面$ mana --help
Traceback (most recent call last):
  File "/home/andrew/.pyenv/versions/3.6.3/bin/mana", line 7, in <module>
    from mana.mana import cli
  File "/home/andrew/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mana/mana.py", line 32, in <module>
    from operators import _mkdir_p
ModuleNotFoundError: No module named 'operators'
```

貌似不支持
``` 
from operators import _mkdir_p
```
这种导入风格，我把所有的这种导入改成下面这样的:

``` python
from .operators import _mkdir_p
```
之后就可以正常运行了。

**Comment by misakar** [comment]
OK
