### ISSUE TITLE
ModuleNotFoundError: No module named 'operators'

### ISSUE THREAD

**Issue by gawinwu** [neo1218/mana#25]
Traceback (most recent call last):
  File "d:\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python36\Scripts\mana.exe\__main__.py", line 5, in <module>
  File "d:\python\python36\lib\site-packages\mana\mana.py", line 32, in <module>
    from operators import _mkdir_p
ModuleNotFoundError: No module named 'operators'

**Comment by zhanggaolei001** [comment]
Save problem for me~
